INPUT_FILE_PATH_NAME = 'scenarios.json'
PROGRESS_FILE_PATH_NAME = 'progress.json'

API_SOURCE = ' http://192.168.1.116:4999/'
API_ENDPOINT_INIT = 'attacker'
API_ENDPOINT_VALIDATE = 'validate'
API_ENDPOINT_VALIDATE2 = 'validate2'
