INPUT_FILE_PATH_NAME = 'scenarios.json'
PROGRESS_FILE_PATH_NAME = 'progress.json'

API_SOURCE = 'http://10.10.54.212:4999/'
API_ENDPOINT_INIT = 'attacker'
API_ENDPOINT_VALIDATE = 'validate'
API_ENDPOINT_VALIDATE2 = 'validate2'
